### ISSUE TITLE
creacion de medidas nuevas

### ISSUE THREAD

**Issue by nextroom** [CostanzoPablo/room#23]
al crear nuevas medidas de fotos, toma los cambios los muestra pero no se pueden utilizar. se cargo 10x15 y 13x18 en ambas superficies, Mate y brillo, se le cargo precio tambien

**Comment by CostanzoPablo** [comment]
Volver a probar, si anda.... Se actualiza el servidor por si faltan subir cambios... Volver a publicar issue si es asi
